version: "3.9"

services:
    app:
        container_name: schnitzeljagd
        image: app
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "3000:3000"
        environment:
            DB_PORT: "27017"
            DB_NAME: "schnitzeljagd-db"
            DB_USER: "user"
            DB_PASSWORD: "password"
        depends_on:
        - db
    db:
        image: mongodb/mongodb-community-server:latest
        restart: unless-stopped
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: "user"
            MONGO_INITDB_ROOT_PASSWORD: "password"
