version: "3.9"

services:
    app:
        container_name: schnitzeljagd
        image: app
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "3000:3000"
        environment:
           - DATABASE_USER=username
           - DATABASE_PASSWORD=password
           - DATABASE_URL=db
           - DATABASE_NAME=users
           - DATABASE_PORT=27017


        depends_on:
        - db
    db:
        image: mongodb/mongodb-community-server:latest
        restart: unless-stopped
        environment:
           - MONGO_INITDB_ROOT_USERNAME=username
           - MONGO_INITDB_ROOT_PASSWORD=password