version: "3.9"

services:
    app:
        container_name: schnitzeljagd
        image: app
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "3000:3000"