version: "3.9"


services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    restart: unless-stopped
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DATABASE_USER
      MONGO_INITDB_ROOT_PASSWORD: $DATABASE_PASSWORD
      MONGO_INITDB_DATABASE: $DATABASE_NAME
    env_file:
      - environment.env  # Hier verwenden wir die .env-Datei, um die Umgebungsvariablen zu laden

  app:
    container_name: schnitzeljagd
    image: app
    restart: unless-stopped
    build:
        context: .
        dockerfile: Dockerfile
        target: base
    ports:
         - "3000:3000"
    environment:
        DATABASE_USER: $DATABASE_USER
        DATABASE_PASSWORD: $DATABASE_PASSWORD
        DATABASE_URL: db
        DATABASE_NAME: $DATABASE_NAME
        DATABASE_PORT: $DATABASE_PORT
    env_file:
      - environment.env  # Hier verwenden wir die .env-Datei, um die Umgebungsvariablen zu laden
    depends_on:
      - mongodb

volumes:
  mongo_data: